name: On new pull request
on: [pull]

jobs:
  action:
    runs-on: ubuntu-latest
    name: Check commits
    steps:
    # - name: Checkout
    #   uses: actions/checkout@v2
    #   with:
    #     fetch-depth: 0
    - name: Update references
      uses: pmarnik/jira-issue-ref-action@master
