name: On new pull request
on: [pull_request]

jobs:
  action:
    runs-on: ubuntu-latest
    name: Check commits
    steps:
    # - name: Checkout
    #   uses: actions/checkout@v2
    #   with:
    #     fetch-depth: 0
    - name: dump repo
      run: echo ${{ github.repository }}
    - name: dump pull number
      run:  echo ${{ github.event.pull_request.number }}

    # - name: Update references
    #   uses: pmarnik/jira-issue-ref-action@master
