name: On new pull request
on:
  pull_request:
    types: [opened]

jobs:
  action:
    runs-on: ubuntu-latest
    name: Update references
    steps:
    - name: Update references
      uses: pmarnik/jira-issue-ref-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-url-pattern: http://onet.pl/234/{issue_key}